server:
  port: 8085

spring:
  application:
    name: MS_Notificacion
  datasource:
    url: jdbc:mysql://localhost:3306/tpi_microservicio1
    password: root
    username: root
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

