server:
  port: 8094

spring:
  application:
    name: MS_Posiciones
  datasource:
    url: jdbc:mysql://localhost:3306/tpi_microservicio1
    password: 123456789
    username: root
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    discovery:
      enabled: true
