server:
  port: 8091

spring:
  application:
    name: MS_Interesados
  datasource:
    url: jdbc:mysql://localhost:3306/tpi_microservicio1
    password: 123456789
    username: root
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka